### ISSUE TITLE
Sheep Updater doesn't run on shutdown

### ISSUE THREAD

**Issue by mrpwes** [knownunown/Sheep#12] opened 2018-02-04 02:29 UTC
Old file 0.0.1 From poggit have a new update 0.0.2 so i updated            ////        the info of the plugin didnt change ..... the name still {PluginName} {OldVersion} Example 0.0.1 But i Already Update It :+1:

**Comment by KnownUnown** [comment] 2018-02-15 04:37
Hey! Two quick questions:

1. You're updating the plugin using Sheep, correct?
2. Are you using the `info` command to check the version?

Thanks!

**Comment by mrpwes** [comment] 2018-03-20 04:58
1. Ya
2. Yes im using info to check version


but when i use default "plugin" command LOOK

"BLUE" Command I Used "Green" The Bug ... about plugin that sheep didnt update it ........ tnx sir

![untitled-1](https://user-images.githubusercontent.com/31194909/37636650-8777c722-2bc0-11e8-92c4-dc25c3d9cbf0.jpg)

**Comment by KnownUnown** [comment] 2018-03-22 03:54
This is probably intended behavior. If Sheep updated the plugin, you have to restart your server for the update to apply. This is a limitation of PocketMine-MP and PHP, not Sheep itself. The newest version ([5.2.1](772d00c1187a4e4094d964446b379f5c840d3f5d)) prints warning messages to the console to notify you that you need to restart the server. If the plugin is not updating after you restart your server, please reopen this issue.

**Comment by mrpwes** [comment] 2018-03-22 05:58
http://www.mediafire.com/file/4v7sgab7yquqcxr/Bug.webm

Look At The Video*

**Comment by KnownUnown** [comment] 2018-03-22 06:02
Oh, your problem is that you are closing your console window to stop the server. Doing this will not let PocketMine or its plugins shutdown correctly. To correctly shut down your server, please use the `stop` command.

**Comment by mrpwes** [comment] 2018-03-22 06:06
ok later ill do im in school now

**Comment by mrpwes** [comment] 2018-03-22 14:12
Didn't Work Sir

**Comment by KnownUnown** [comment] 2018-03-22 15:46
The issue is with MinTTY and PHP. On Windows, PocketMine force-stops PHP to work around the CommandReader blocking because MinTTY is pipe based. This force stops prevent Sheep Updater from running because it's a shutdown function.

**Comment by mrpwes** [comment] 2018-03-23 01:47
so what are we going to do ? , Should we wait for next updates ?

**Comment by KnownUnown** [comment] 2018-03-24 02:13
Yes, another workaround would be to use PowerShell to run the server.

**Comment by mrpwes** [comment] 2018-03-24 02:51
Thanks :)

**Comment by mrpwes** [comment] 2018-05-21 13:47
i can test your plugins before you want to upload it .. so i can help those windows users .

**Closed** 2019-05-22 02:16 UTC
Labels: Sheep: Core, bug, windows
