### ISSUE TITLE
Use another function instead of a shutdown function to update plugins using Sheep

### ISSUE THREAD

**Issue by XuPaperCup** [KnownUnown/Sheep#14] opened 2018-05-28 11:27 UTC
# Report a bug:

## Information
Using:
Sheep v5.2.2
PocketMine-MP verison:1.7dev-1058
API:3.0.0-ALPHA12
## Description
Bug 1: It can,t auto detect and update plugin(s)
Bug 2: I can't update plugin using sheep!

**Watch the video below.**
## Video
Link:
http://www.mediafire.com/file/zz15nj7d0jf0nr5/%E9%8C%84%E8%A3%BD_2018_05_28_19_00_51_462.mp4

Ask me if you need more infomation.
Please help to fix the bug,thank you.

**Comment by XuPaperCup** [comment] 2018-05-28 11:52
After that I check with info command, it update.But the name no change like https://github.com/KnownUnown/Sheep/issues/12. But it still a bug is that it don't auto update plugin(s)

**Comment by mrpwes** [comment] 2018-05-28 14:15
like i said ... same issue here

**Comment by XuPaperCup** [comment] 2018-05-28 14:26
Why that using info command can show a new version and pl command no ? Their are really some issues here...

**Comment by KnownUnown** [comment] 2018-05-29 03:50
Duplicate of #12 - the Sheep Updater registers a shutdown function to update plugins. On Windows, there is a bug that prevents PocketMine from shutting down correctly. They have worked around this by killing the server on shutdown, which does not allow Sheep Updater to run. As mentioned in #12, this bug can be fixed by running the server using `start.ps1` instead of `start.cmd`.

**Comment by XuPaperCup** [comment] 2018-05-29 11:22
I wanna to know that can you use another way to update?Which means that don't use shutdown function to update plugin(s),use another function to update plugin(s),like that I sometimes use instead of using a update command⬇
## How to update a plugins (s) with no using update command:
**First**,use uninstall command to uninstall/delete the old version
**Then**,use a install command to install back the new version
**Finally**,use reload or stop command to reload/restart the server,done.
### A quick question:
I want to know that why when we need to use restart command to apply the plugin(s), can't it just use reload command itself?

**Comment by XuPaperCup** [comment] 2018-05-29 23:16
... but when it stop , it can't update.
Like that KnownUnown said:

The Sheep Updater registers a shutdown function to update plugins. On Windows, there is a bug that prevents PocketMine from shutting down correctly. They have worked around this by killing the server on shutdown, which does not allow Sheep Updater to run. As mentioned in #12, this bug can be fixed by running the server using start.ps1 instead of start.cmd.

**Comment by KnownUnown** [comment] 2018-05-30 01:05
Server stop works correctly if you use the powershell start script. Reload behavior is buggy and there is some undefined behavior when you replace phars on unload. The MinTTY stop issue is tracked at #12, closing this duplicate.

**Closed by KnownUnown** 2018-05-30 01:05 UTC
